{
  "openapi": "3.0.2",
  "info": {
    "title": "Shoping Cart RestFul Api",
    "version": "1.0",
    "description": "Api for shoping cart RestFul API",
    "contact": {
      "name": "Dedi Syaputra",
      "email": "dedisyaputra611@gmail.com"
    }
  },
  "servers": [
    {
      "url": "http://localhost:3200/{environtment}/api/v1",
      "description": "Shoping cart RestFul Api server",
      "variables": {
        "environtment": {
          "default": "dev",
          "description": "Server environtment",
          "enum": ["dev", "qa", "prod"]
        }
      }
    }
  ],
  "paths": {
    "/register": {
      "post": {
        "tags": ["Authentication"],
        "summary": "create new users",
        "responses": {
          "201": {
            "description": "success create new user",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": { "type": "integer" },
                    "name": { "type": "string" },
                    "email": { "type": "string" },
                    "password": { "type": "string" },
                    "phone_number": { "type": "integer", "nullable": true },
                    "address": {
                      "type": "object",
                      "properties": {
                        "city": { "type": "string" },
                        "street": { "type": "string" }
                      },
                      "nullable": true
                    }
                  }
                },
                "example": {
                  "register user": {
                    "value": {
                      "id": 1,
                      "name": "user 1",
                      "email": "user1@gmail.com",
                      "password": "password",
                      "phone_number": "0832883232",
                      "address": {
                        "city": "Ranai",
                        "street": "Jalan Pattimura"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "failed create new user",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": { "type": "string" }
                  }
                },
                "examples": {
                  "password error": {
                    "value": {
                      "errors": "minLength password must be 8 characters"
                    }
                  },
                  "name error": {
                    "value": {
                      "errors": "name minLength must be 4 characters"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "errors": { "type": "string" } }
                }
              }
            }
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "minLength": 4,
                    "maxLength": 100,
                    "required": ["true"]
                  },
                  "email": {
                    "type": "string",
                    "minLength": 8,
                    "maxLength": 100,
                    "required": ["true"]
                  },
                  "password": {
                    "type": "string",
                    "minLength": 8,
                    "required": ["true"]
                  },
                  "phone_number": {
                    "type": "number",
                    "minLength": 12,
                    "maxLength": 12,
                    "nullable": true
                  },
                  "address": {
                    "type": "object",
                    "properties": {
                      "city": {
                        "type": "string",
                        "minLength": 4,
                        "nullable": true
                      },
                      "street": {
                        "type": "string",
                        "minLength": 4,
                        "nullable": true
                      }
                    }
                  },
                  "token": {
                    "type": "string",
                    "nullable": true
                  }
                }
              },
              "examples": {
                "user 1": {
                  "value": {
                    "name": "user 1",
                    "email": "user1@gmail.com",
                    "password": "password",
                    "phone_number": "0832883232",
                    "address": {
                      "city": "Ranai",
                      "street": "Jalan Pattimura"
                    }
                  }
                },
                "user 2": {
                  "value": {
                    "name": "user 2",
                    "email": "user2@gmail.com",
                    "password": "password",
                    "phone_number": "083288323233",
                    "address": {
                      "city": "Jakarta",
                      "street": "Jalan Ali Hasyim"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "tags": ["Authentication"],
        "summary": "login for users",
        "description": "api for login users",
        "responses": {
          "200": {
            "description": "login success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": { "type": "string" }
                  }
                },
                "example": {
                  "login success": {
                    "value": {
                      "token": "94893f94h3f93h4hf943hf902h0r44hr"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "login failed",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "login failed": {
                    "value": {
                      "errors": "email or password wrong"
                    }
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "minLength": 8,
                    "required": ["true"]
                  },
                  "password": {
                    "type": "string",
                    "minLength": 8,
                    "required": ["true"]
                  }
                }
              },
              "examples": {
                "user 1": {
                  "value": {
                    "email": "user1@gmail.com",
                    "password": "password"
                  }
                },
                "user 2": {
                  "value": {
                    "email": "user2@gmail.com",
                    "password": "password"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/products": {
      "get": {
        "tags": ["Products"],
        "summary": "get all data products",
        "responses": {
          "200": {
            "description": "get all data products",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": { "type": "integer" },
                      "image": { "type": "string" },
                      "name": { "type": "string" },
                      "stock": { "type": "integer" },
                      "price": { "type": "integer" },
                      "category": {
                        "type": "object",
                        "properties": { "name": { "type": "string" } }
                      },
                      "description": { "type": "string" }
                    }
                  }
                },
                "example": {
                  "value": [
                    {
                      "id": 1,
                      "image": "product-001.jpg",
                      "name": "Baju Koko",
                      "stock": 115,
                      "price": 20000,
                      "category": {
                        "name": "pakaian muslim"
                      },
                      "description": "baju koko muslim pria cocok untuk kawula muda"
                    },
                    {
                      "id": 2,
                      "image": "product-002.jpg",
                      "name": "Baju gamis",
                      "stock": 200,
                      "price": 30000,
                      "category": {
                        "name": "pakaian muslim"
                      },
                      "description": "baju gamis wanita cocok untuk kawula muda"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/products/{productName}": {
      "get": {
        "tags": ["Products"],
        "summary": "get specific product data",
        "responses": {
          "200": {
            "description": "responses api get product by name",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": { "type": "integer" },
                    "image": { "type": "string" },
                    "name": { "type": "string" },
                    "stock": { "type": "integer" },
                    "price": { "type": "integer" },
                    "category": {
                      "type": "object",
                      "properties": { "name": { "type": "string" } }
                    },
                    "description": { "type": "string" }
                  }
                },
                "example": {
                  "value": {
                    "id": 2,
                    "image": "product-002.jpg",
                    "name": "Baju gamis",
                    "stock": 200,
                    "price": 30000,
                    "category": {
                      "name": "pakaian muslim"
                    },
                    "description": "baju gamis wanita cocok untuk kawula muda"
                  }
                }
              }
            }
          },
          "404": {
            "description": "error not found product",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": { "type": "string" }
                  }
                },
                "example": {
                  "value": {
                    "errors": "product not found"
                  }
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "productName",
            "in": "path",
            "required": true,
            "description": "productName for get specific product",
            "schema": {
              "type": "string",
              "minLength": 4,
              "maxLength": 100
            }
          }
        ]
      },
      "post": {
        "tags": ["Products"],
        "summary": "add product to cart",
        "requestBody": {
          "content": {
            "headers": {
              "schema": {
                "type": "object",
                "required": ["true"],
                "title": "Authorization"
              },
              "example": {
                "value": {
                  "Authorization": "s948439fh93f89h439hf484h"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": " success add product to cart",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": { "type": "integer" },
                    "product_id": { "type": "integer" },
                    "user_id": { "type": "integer" },
                    "quantity": { "type": "integer" }
                  }
                },
                "example": {
                  "value": {
                    "id": 1,
                    "product_id": 2,
                    "user_id": 1,
                    "quantity": 2
                  }
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "productName",
            "in": "path",
            "required": true,
            "description": "productName for add specific product to cart",
            "schema": { "type": "string", "minLength": 4, "maxLength": 100 }
          }
        ]
      }
    },
    "/cart": {
      "get": {
        "tags": ["Cart"],
        "summary": "get all data cart",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": ["true"],
                "title": "Authorization"
              },
              "example": {
                "value": {
                  "Authorization": "s948439fh93f89h439hf484h"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "success get all data cart",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": { "type": "integer" },
                      "product_id": { "type": "integer" },
                      "user_id": { "type": "integer" },
                      "quantity": { "type": "integer" }
                    }
                  }
                },
                "example": {
                  "value": [
                    {
                      "id": 1,
                      "product_id": 3,
                      "user_id": 1,
                      "quantity": 3
                    },
                    {
                      "id": 2,
                      "product_id": 2,
                      "user_id": 1,
                      "quantity": 3
                    },
                    {
                      "id": 3,
                      "product_id": 3,
                      "user_id": 2,
                      "quantity": 1
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/cart/address": {
      "post": {
        "tags": ["Cart"],
        "summary": "create address for product data",
        "responses": {},
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "address": {
                    "type": "object",
                    "properties": {
                      "city": {
                        "type": "string",
                        "minLength": 4,
                        "required": ["true"]
                      },
                      "street": {
                        "type": "string",
                        "minLength": 4,
                        "required": ["true"]
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/cart/{productName}": {
      "delete": {
        "tags": ["Cart"],
        "summary": "delete specific product",
        "responses": {},
        "parameters": [
          {
            "name": "productName",
            "in": "path",
            "required": true,
            "description": "productName for delete specific product from cart",
            "schema": { "type": "string", "minLength": 4, "maxLength": 100 }
          }
        ]
      }
    },
    "/cart/checkout": {
      "post": {
        "tags": ["Cart"],
        "summary": "checkout product from cart",
        "responses": {},
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "total_product": {
                    "type": "number",
                    "minLength": 1,
                    "required": ["true"]
                  },
                  "price": { "type": "number", "required": ["true"] },
                  "address": {
                    "type": "object",
                    "properties": {
                      "city": {
                        "type": "string",
                        "minLength": 4,
                        "required": ["true"]
                      },
                      "street": {
                        "type": "string",
                        "minLength": 4,
                        "required": ["true"]
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "parameters": {
      "productName": {
        "name": "productName",
        "in": "path",
        "required": true,
        "description": "productName for get specific product",
        "schema": {
          "type": "string",
          "minLength": 4,
          "maxLength": 100
        }
      }
    },
    "schemas": {}
  }
}
